This parser is intended to get data from participants.db. Get the data in the following procedure:

1. Open the terminal and type:
    python parser.py <path to your participants.db>
2. The data will be stored in experiment_data/, which should be a folder generated by parser.py. The data files are named by convention: assignmentID_workerID_hitID_{doublet, subject, triplet}. In other words, each experiment data generated by a worker will be splitter into three files. The format of each file is as follows:

Doublet Data:
Column 1: trial_index_global (The larger this number is, the later the worker did this trial.
Column 2: react_time
Column 3: similarity score
Column 4: two stimuli (paths to the images), separated by a comma

Triplet Data:
Column 1: trial_index_global
Column 2: react_time
Column 3: two images pressed by worker. Each is denoted by one of the words {top, left, right}. They are separated by a comma.
Column 4: three stimuli (paths to the images), separated by a comma

Subject Data:
Column 1: assignment ID
Column 2: worker ID
Column 3: hit ID
Column 4: age
Column 5: gender
Column 6: sexual orientation
Column 7: races, separated by a comma
Column 8: comRaces, separated by a comma
